--- #YAML:1.0
name:               Geo-Distance-XS
version:            0.08
abstract:           speed up Geo::Distance
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.82
requires:
    Geo::Distance:  0.16
    Test::More:     0
resources:
    repository:  http://github.com/gray/geo-distance-xs
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
